export const actionTypes = {
	GET_TODOLIST: 'GET_TODOLIST',
	UPDATE_TODOLIST: 'UPDATE_TODOLIST',
	DEL_TODOLIST: 'DEL_TODOLIST',
	ADD_TODOLIST: 'ADD_TODOLIST',
	GET_ARTICLE: 'GET_ARTICLE',
	ADD_ARTICLE: 'ADD_ARTICLE',
	UPDATE_ARTICLE: 'UPDATE_ARTICLE',
	DEL_ARTICLE: 'DEL_ARTICLE',
}
